### ISSUE TITLE
Feature request: configure whether or not to execute the closure before any delay

### ISSUE THREAD

**Issue by Ploppz** [johndiiorio/react-useinterval#4]
In my case, I would like the closure to be called as soon as possible, and then to wait N seconds between every subsequent call. Will you consider adding an option for that?

**Comment by johndiiorio** [comment]
Hi. Thanks for your feature request. While a nice idea, I have two concerns with this feature:

1. I don't think this feature could be added without a breaking change. The current syntax is `useInterval(callback, delay, ...args)`. If instead we did something like `useInterval(callback, delay, config, ...args)` where config could be `{ runImmediate: true }`, this could break code that expected the `...args` to be forwarded to `callback`.
2. The corresponding `setInterval` function in JavaScript does not have this behavior or a parameter. In JavaScript, one could do:
```
myFunction();
setInterval(myFunction, 3000);
```
With React hooks, one can use a `useEffect` to achieve this.
```
useEffect(myFunction, []);
useInterval(myFunction, 3000);
```

**Comment by Ploppz** [comment]
I see. Feel free to close.
